
-- Dados da tabela paginas
-- Gerando em: 02/08/2018 10:25:16
-- Pelo Gerador JK-19

TRUNCATE `paginas`;

-- Dados da tabela: 
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 2, 1, 'ed44_pag_1.jpg', 'ed44_min_pag_1.jpg', 1, '2018-07-13 14:33:04', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 3, 2, 'ed44_pag_2.jpg', 'ed44_min_pag_2.jpg', 1, '2018-07-13 14:34:47', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 4, 3, 'ed44_pag_3.jpg', 'ed44_min_pag_3.jpg', 1, '2018-07-13 14:34:58', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 5, 4, 'ed44_pag_4.jpg', 'ed44_min_pag_4.jpg', 1, '2018-07-13 14:35:09', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 6, 5, 'ed44_pag_5.jpg', 'ed44_min_pag_5.jpg', 1, '2018-07-13 14:35:24', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 7, 6, 'ed44_pag_6.jpg', 'ed44_min_pag_6.jpg', 1, '2018-07-13 14:35:35', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 8, 7, 'ed44_pag_7.jpg', 'ed44_min_pag_7.jpg', 1, '2018-07-13 14:35:51', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 9, 8, 'ed44_pag_8.jpg', 'ed44_min_pag_8.jpg', 1, '2018-07-13 14:36:03', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 10, 1, 'ed45_pag_1.jpg', 'ed45_min_pag_1.jpg', 2, '2018-07-13 14:45:40', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 11, 2, 'ed45_pag_2.jpg', 'ed45_min_pag_2.jpg', 2, '2018-07-13 14:44:30', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 12, 3, 'ed45_pag_3.jpg', 'ed45_min_pag_3.jpg', 2, '2018-07-13 14:44:39', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 13, 4, 'ed45_pag_4.jpg', 'ed45_min_pag_4.jpg', 2, '2018-07-13 14:44:50', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 14, 5, 'ed45_pag_5.jpg', 'ed45_min_pag_5.jpg', 2, '2018-07-13 14:45:02', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 15, 6, 'ed45_pag_6.jpg', 'ed45_min_pag_6.jpg', 2, '2018-07-13 14:45:10', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 16, 7, 'ed45_pag_7.jpg', 'ed45_min_pag_7.jpg', 2, '2018-07-13 14:45:18', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 17, 8, 'ed45_pag_8.jpg', 'ed45_min_pag_8.jpg', 2, '2018-07-13 14:45:28', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 18, 1, 'ed46_pag_1.jpg', 'ed46_min_pag_1.jpg', 3, '2018-07-13 14:54:21', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 19, 2, 'ed46_pag_2.jpg', 'ed46_min_pag_2.jpg', 3, '2018-07-13 14:54:42', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 20, 3, 'ed46_pag_3.jpg', 'ed46_min_pag_3.jpg', 3, '2018-07-13 14:54:55', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 21, 4, 'ed46_pag_4.jpg', 'ed46_min_pag_4.jpg', 3, '2018-07-13 14:55:07', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 22, 5, 'ed46_pag_5.jpg', 'ed46_min_pag_5.jpg', 3, '2018-07-13 14:55:22', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 23, 6, 'ed46_pag_6.jpg', 'ed46_min_pag_6.jpg', 3, '2018-07-13 14:55:36', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 24, 7, 'ed46_pag_7.jpg', 'ed46_min_pag_7.jpg', 3, '2018-07-13 14:55:46', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 25, 8, 'ed46_pag_8.jpg', 'ed46_min_pag_8.jpg', 3, '2018-07-13 14:55:56', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 26, 1, 'ed47_pag_1.jpg', 'ed47_min_pag_1.jpg', 4, '2018-07-13 15:03:07', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 27, 2, 'ed47_pag_2.jpg', 'ed47_min_pag_2.jpg', 4, '2018-07-13 15:03:20', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 28, 3, 'ed47_pag_3.jpg', 'ed47_min_pag_3.jpg', 4, '2018-07-13 15:03:31', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 29, 4, 'ed47_pag_4.jpg', 'ed47_min_pag_4.jpg', 4, '2018-07-13 15:03:46', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 30, 5, 'ed47_pag_5.jpg', 'ed47_min_pag_5.jpg', 4, '2018-07-13 15:04:00', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 31, 6, 'ed47_pag_6.jpg', 'ed47_min_pag_6.jpg', 4, '2018-07-13 15:04:13', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 32, 7, 'ed47_pag_7.jpg', 'ed47_min_pag_7.jpg', 4, '2018-07-13 15:04:24', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 33, 8, 'ed47_pag_8.jpg', 'ed47_min_pag_8.jpg', 4, '2018-07-13 15:04:37', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 34, 1, 'ed49_pag_1.jpg', 'ed49_min_pag_1.jpg', 5, '2018-07-13 15:15:03', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 35, 2, 'ed49_pag_2.jpg', 'ed49_min_pag_2.jpg', 5, '2018-07-13 15:15:15', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 36, 3, 'ed49_pag_3.jpg', 'ed49_min_pag_3.jpg', 5, '2018-07-13 15:15:28', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 37, 4, 'ed49_pag_4.jpg', 'ed49_min_pag_4.jpg', 5, '2018-07-13 15:15:41', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 38, 5, 'ed49_pag_5.jpg', 'ed49_min_pag_5.jpg', 5, '2018-07-13 15:15:52', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 39, 6, 'ed49_pag_6.jpg', 'ed49_min_pag_6.jpg', 5, '2018-07-13 15:16:06', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 40, 7, 'ed49_pag_7.jpg', 'ed49_min_pag_7.jpg', 5, '2018-07-13 15:16:18', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 41, 8, 'ed49_pag_8.jpg', 'ed49_min_pag_8.jpg', 5, '2018-07-13 15:16:27', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 42, 1, 'ed50_pag_1.jpg', 'ed50_min_pag_1.jpg', 6, '2018-07-13 15:23:25', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 43, 2, 'ed50_pag_2.jpg', 'ed50_min_pag_2.jpg', 6, '2018-07-13 15:23:35', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 44, 3, 'ed50_pag_3.jpg', 'ed50_min_pag_3.jpg', 6, '2018-07-13 15:23:45', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 45, 4, 'ed50_pag_4.jpg', 'ed50_min_pag_4.jpg', 6, '2018-07-13 15:23:58', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 46, 5, 'ed50_pag_5.jpg', 'ed50_min_pag_5.jpg', 6, '2018-07-13 15:24:16', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 47, 6, 'ed50_pag_6.jpg', 'ed50_min_pag_6.jpg', 6, '2018-07-13 15:24:30', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 48, 7, 'ed50_pag_7.jpg', 'ed50_min_pag_7.jpg', 6, '2018-07-13 15:24:43', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 49, 8, 'ed50_pag_8.jpg', 'ed50_min_pag_8.jpg', 6, '2018-07-13 15:24:54', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 50, 1, 'ed52_pag_1.jpg', 'ed52_min_pag_1.jpg', 7, '2018-07-13 15:33:18', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 51, 2, 'ed52_pag_2.jpg', 'ed52_min_pag_2.jpg', 7, '2018-07-13 15:33:29', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 52, 3, 'ed52_pag_3.jpg', 'ed52_min_pag_3.jpg', 7, '2018-07-13 15:33:39', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 53, 4, 'ed52_pag_4.jpg', 'ed52_min_pag_4.jpg', 7, '2018-07-13 15:33:49', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 54, 5, 'ed52_pag_5.jpg', 'ed52_min_pag_5.jpg', 7, '2018-07-13 15:33:57', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 55, 6, 'ed52_pag_6.jpg', 'ed52_min_pag_6.jpg', 7, '2018-07-13 15:34:05', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 56, 7, 'ed52_pag_7.jpg', 'ed52_min_pag_7.jpg', 7, '2018-07-13 15:34:14', 1, 1);
INSERT INTO paginas ( `id_paginas`, `numero_da_pagina_paginas`, `imagem_paginas`, `imagem_miniatura_paginas`, `new_sjt_id`, `data_atualizacao_paginas`, `usuario_id`, `bool_ativo_paginas`) VALUES ( 57, 8, 'ed52_pag_8.jpg', 'ed52_min_pag_8.jpg', 7, '2018-07-13 15:34:22', 1, 1);