
-- Criar tabela cpritens_dup
-- Gerando em: 01/08/2018 16:50:25
-- Pelo Gerador JK-19

DROP TABLE IF EXISTS `cpritens_dup`;

CREATE TABLE IF NOT EXISTS `cpritens_dup` (
	`SERIE` char(3) NOT NULL PRIMARY KEY ,
	`Filial` int(11) NOT NULL PRIMARY KEY ,
	`DUPLICATA` char(8) NOT NULL PRIMARY KEY ,
	`SEQUENCIA` varchar(9) NOT NULL PRIMARY KEY ,
	`Cliente` char(6)  ,
	`BANCO` int(11)  ,
	`VENCIMENTO` datetime  ,
	`VALOR_DUPLIC` float  ,
	`DATA_PAGAMENTO` datetime  ,
	`JUROS` float  ,
	`DESCONTO` float  ,
	`OBSERVACAO` longtext  ,
	`TITULO` varchar(6)  ,
	`BOLETO` varchar(15)  ,
	`OBSERVACAOBOLETO1` varchar(84)  ,
	`OBSERVACAOBOLETO2` varchar(84)  ,
	`OBSERVACAOBOLETO3` varchar(84)  ,
	`OBSERVACAOBOLETO4` varchar(84)  ,
	`IMPRESSAO` int(1)  ,
	`FilialBaixa` int(11)  ,
	`ReciboBaixa` decimal(10,0)  ,
	`NRO_CONTA` char(15)  ,
	`ContaContabilPagar` char(5)  ,
	`TransmitidoContab` int(1)  ,
	`DataAtualizacao` datetime  ,
	`HoraAtualizacao` char(8)  ,
	`UsuarioAtualizacao` char(3)  ,
	`Cupom` varchar(6)  ,
	`Troca` varchar(6)  ,
	`VencTroca` datetime  ,
	`TipoRecebimento` int(11)  ,
	`DuplicataBanco` int(1)  ,
	`fazenda` int(11)  ,
	`DuplicataGarantida` int(1)  ,
	`CondPagamento` int(11)  ,
	`DataEstorno` datetime  ,
	`RemessaBoleto` int(1)  ,
	`DocumentoRemessa` varchar(6)  ,
	`CodBarras` varchar(44)  ,
	`LinhaDigitavel` varchar(62)  ,
	`ArqRemessa` varchar(8)  ,
	`TipoBoleto` char(1)  ,
	`HistoricoCobranca` varchar(500)  ,
	`DataHistoricoCobranca` datetime  ,
	`Programacao` datetime  ,
	`NossoNumero` char(11)  ,
	`Financiamento` int(1)  ,
	`Loteamento` int(11)  ,
	`ParcEntrada` int(1)  ,
	`VencimentoOriginal` datetime  ,
	`ValorOriginal` float  ,
	`Cartorio` int(1)  ,
	`DocumentoVendaLote` varchar(6)  ,
	`DataReajuste` datetime  ,
	`HoraReajuste` char(8)  ,
	`UsuarioReajuste` varchar(3)  ,
	`ValorAnterior` float  ,
	`TaxaReajuste` float  ,
	`FECHAMENTO` varchar(6)  ,
	`RemessaSantander` int(1) NOT NULL ,
	`ClienteBoleto` int(11)  ,
	`NumSeqAgrupado` int(11)  ,
	`ObservacaoBoleto` varchar(200)  ,
	`VencimentoRetorno` datetime  ,
	`OcorrenciaRetorno` int(11)  ,
	`DataOcorrenciaRetorno` datetime  ,
	`JurosRetorno` float  ,
	`DescontoRetorno` float  ,
	`TotalRecebidoRetorno` float  ,
	`SeuNumero` varchar(10)  ,
	`ObservacaoBoletoAutomatica` varchar(8000)  ,
	`Insolventes` int(1)  ,
	`DataBaixaAviso` datetime  ,
	`UsuarioBaixaAviso` char(3)  ,
	`DataEntradaBanco` datetime  ,
	`MotivoRejeicoesRetorno` varchar(50)  ,
	`DataLembrete1` datetime  ,
	`DataLembrete2` datetime  ,
	`RemessaSafra` int(11)  ,
	`RemessaItau` int(11)  ,
	`ValorCorrecao` float  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- Dados da tabela: Nenhum registro