

--
-- Database AMFIOS 
-- Registros
-- Criado Pelo /******* Migration JK-19 *********/
-- Gerado: 21/12/2017 17:20:27
--   _       _          __     ___             ______        _____     ___                 ___  
-- // \\  // \\  ||   //  \\  ||  \\    //\\     ||    ||   //   \\  ||   ||       //||  //   ||
-- ||  \\//  ||  ||   || __   ||__//   //__\\    ||    ||   ||   ||  ||   ||  ===    ||  ||___||
-- ||        ||  ||   \\__//  ||  \\  //    \\   ||    ||   \\___//  ||   ||         ||   ____||
--

USE AMFIOS;


DROP TABLE IF EXISTS `ITEM`;
CREATE TABLE ITEM (
	`GRUPO` int NOT NULL,
	`SUB_GRUPO` int NOT NULL,
	`ITEM` int NOT NULL,
	`DESCRICAO` varchar(300) DEFAULT NULL,
	`DESCRICAONF` varchar(300) DEFAULT NULL,
	`REFERENCIA1` varchar(70) DEFAULT NULL,
	`REFERENCIA2` varchar(70) DEFAULT NULL,
	`UNIDADE_MEDIDA` varchar(3) DEFAULT NULL,
	`UNIDADE_MEDIDA_VENDA` varchar(3) DEFAULT NULL,
	`LOCALIZACAO` varchar(20) DEFAULT NULL,
	`ATUALIZA_ESTOQUE` int(1) NOT NULL,
	`ALMOXARIFADO` int DEFAULT NULL,
	`PESO_UNITARIO` float DEFAULT NULL,
	`COMISSAO` float DEFAULT NULL,
	`INDICE_PRECO1` float DEFAULT NULL,
	`INDICE_PRECO2` float DEFAULT NULL,
	`INDICE_PRECO3` float DEFAULT NULL,
	`INDICE_PRECO4` float DEFAULT NULL,
	`COD_TRIBUTACAO` int DEFAULT NULL,
	`CLASSIF_FISCAL` char(20) DEFAULT NULL,
	`ESTOQUE` numeric DEFAULT NULL,
	`ESTOQUE_INICIAL` float DEFAULT NULL,
	`PRECO_MEDIO` float DEFAULT NULL,
	`PRECO_INICIAL` float DEFAULT NULL,
	`ESTOQUE_MINIMO` float DEFAULT NULL,
	`ULTIMA_COMPRA` datetime DEFAULT NULL,
	`RECEITUARIO` int(1) NOT NULL,
	`DataAtualizacao` datetime DEFAULT NULL,
	`HoraAtualizacao` char(8) DEFAULT NULL,
	`UsuarioAtualizacao` char(3) DEFAULT NULL,
	`MOVIMENTA_LOJA` int(1) NOT NULL,
	`BLOQUEADO` int(1) NOT NULL,
	`VENCIMENTO` datetime DEFAULT NULL,
	`MARGEMLUCRO` float DEFAULT NULL,
	`CODIGO_BARRAS` varchar(14) DEFAULT NULL,
	`OBSERVACAONOTA` numeric DEFAULT NULL,
	`PERCFORAESTADO` float DEFAULT NULL,
	`SACAS_TROCA` float DEFAULT NULL,
	`CATEGORIA` int DEFAULT NULL,
	`QTDEEMBALAGEM` float DEFAULT NULL,
	`MEDIDA` float DEFAULT NULL,
	`CARGA` char(10) DEFAULT NULL,
	`TOPO` varchar(50) DEFAULT NULL,
	`CARACTERISTICA` char(20) DEFAULT NULL,
	`MOV_ALMOXARIF` int(1) DEFAULT NULL,
	`TIPOPRODUTO` int DEFAULT NULL,
	`PERCENTRADA` float DEFAULT NULL,
	`QTDEM3` float DEFAULT NULL,
	`IMOBILIZADO` int(1) DEFAULT NULL,
	`PRODUCAO` int(1) DEFAULT NULL,
	`PESO_ACO` float DEFAULT NULL,
	`FatorProdutividade` float DEFAULT NULL,
	`ObservacaoProducao_Barras` varchar(500) DEFAULT NULL,
	`BeneficioFiscal` int(1) DEFAULT NULL,
	`RelDiasVida` int(1) DEFAULT NULL,
	`MateriaPrima` int(1) DEFAULT NULL,
	`BloquearTransferencia` int(1) DEFAULT NULL,
	`SomenteMultiplos` int(1) DEFAULT NULL,
	`BloquearEstoqueNegativo` int(1) DEFAULT NULL,
	`Origem` int DEFAULT NULL,
	`Fabricante` varchar(100) DEFAULT NULL,
	`PesoAdicional` float DEFAULT NULL,
	`rowguid` varchar(500) NOT NULL,
	`Maximo` float DEFAULT NULL,
	`CodigoProdutoNF` int DEFAULT NULL,
	`SequenciaTalao` int DEFAULT NULL,
	`CodTipoItem` int DEFAULT NULL,
	`CodGenero` int DEFAULT NULL,
	`CodServico` int DEFAULT NULL,
	`IdMercadoria` int DEFAULT NULL,
	`PercPIS` float DEFAULT NULL,
	`PercCOFINS` float DEFAULT NULL,
	`CST_PIS_COFINS` char(2) DEFAULT NULL,
	`PercColuna001` float DEFAULT NULL,
	`PercColuna002` float DEFAULT NULL,
	`PercColuna003` float DEFAULT NULL,
	`PercColuna004` float DEFAULT NULL,
	`PercColuna005` float DEFAULT NULL,
	`CST_PIS_COFINS_Entrada` char(2) DEFAULT NULL,
	`Numero` varchar(3) DEFAULT NULL,
	`Embalagem` int DEFAULT NULL,
	`Marca` int DEFAULT NULL,
	`Sabor` int DEFAULT NULL,
	`TipoConsumo` int DEFAULT NULL,
	`ValorMaxNota` float DEFAULT NULL,
	`ValorMaxEntrada` float DEFAULT NULL,
	`ControlaEstoqueMinimo` int(1) DEFAULT NULL,
	`HorasProducao` char(8) DEFAULT NULL,
	`QtdeCola` float DEFAULT NULL,
	`QtdeRebite` float DEFAULT NULL,
	`UsuarioHorasProducao` varchar(250) DEFAULT NULL,
	`CodigoANP` varchar(9) DEFAULT NULL,
	`Especificacoes` varchar(2000) DEFAULT NULL,
	`Cliente` int DEFAULT NULL,
	`AlertaEstoqueMinimo` int(1) DEFAULT NULL,
	`DescPercPIS` float DEFAULT NULL,
	`DescPercCOFINS` float DEFAULT NULL,
	`IncideIpiPisCofins` int(1) DEFAULT NULL,
	`NaoIncideIpiPisCofins` int(1) DEFAULT NULL,
	`CK_PESO` int(1) DEFAULT NULL,
	`NaturezaReceita` int DEFAULT NULL,
	`BCCredito` int DEFAULT NULL,
	`TipoCredito` int DEFAULT NULL,
	`CubagemUN` float DEFAULT NULL,
	`CubagemCaixa` float DEFAULT NULL,
	`ciaf` varchar(50) DEFAULT NULL,
	`DescricaoAntiga` varchar(300) DEFAULT NULL
	-- ,
	-- PRIMARY KEY (`GRUPO`, `SUB_GRUPO`, `ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


