
USE PointDaPanqueca;

TRUNCATE CondPagamento;
INSERT INTO CondPagamento (Codigo,DESCRICAO) VALUES (1, "DINHEIRO");
INSERT INTO CondPagamento (Codigo,DESCRICAO) VALUES (2, "CHEQUE");
INSERT INTO CondPagamento (Codigo,DESCRICAO) VALUES (3, "CARTÃO DE CRÉDITO");
INSERT INTO CondPagamento (Codigo,DESCRICAO) VALUES (4, "CARTÃO DE DÉBITO");
INSERT INTO CondPagamento (Codigo,DESCRICAO) VALUES (7, "CLIENTES ANTECIPADOS");
INSERT INTO CondPagamento (Codigo,DESCRICAO) VALUES (8, "CARTEIRA");
INSERT INTO CondPagamento (Codigo,DESCRICAO) VALUES (9, "REFEIÇÃO");
INSERT INTO CondPagamento (Codigo,DESCRICAO) VALUES (10, "CIELO VR");
INSERT INTO CondPagamento (Codigo,DESCRICAO) VALUES (11, "CIELO VR CREDITO");
INSERT INTO CondPagamento (Codigo,DESCRICAO) VALUES (12, "CARTAO PENDENTE");