
USE PointDaPanqueca;

TRUNCATE TabAdicionalProdutosItens;
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 8, "KG ", 0.035, 137);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 7, "KG ", 0.035, 140);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 2, "KG ", 0.035, 129);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 4, "KG ", 0.035, 136);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 3, "KG ", 0.035, 130);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 10, "KG ", 0.117, 128);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 9, "KG ", 0.035, 134);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 13, "KG ", 0.035, 127);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 14, "KG ", 0.035, 141);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 15, "KG ", 0.1, 131);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 16, "KG ", 0.035, 132);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 613, "UN ", 0.05, 139);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 618, "KG ", 0.035, 138);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 619, "KG ", 0.035, 135);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (1, 617, "KG ", 0.035, 133);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (2, 3, "KG ", 0.1, 82);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (2, 18, "KG ", 0.1, 86);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (2, 617, "KG ", 0.1, 83);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (2, 618, "KG ", 0.1, 85);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (2, 619, "KG ", 0.1, 84);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (3, 3, "KG ", 0.1, 87);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (3, 9, "KG ", 0.1, 88);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (3, 18, "KG ", 0.1, 89);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (4, 15, "KG ", 0.3, 94);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (4, 24, "KG ", 0.1, 93);
INSERT INTO TabAdicionalProdutosItens (Codigo,Item,Unidade,QUANTIDADE,ID_TabAdicionalProdutosItens) VALUES (4, 25, "KG ", 0.3, 95);