
-- Dados da tabela config_login
-- Gerando em: 05/08/2018 23:35:02
-- Pelo Gerador JK-19

TRUNCATE `config_login`;

-- Dados da tabela: 
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 5, '29/12/2017 04:09:17', 2, 7, 'usuario', 'login_usuario', 'senha_usuario', '#acd7f0', 1, 5);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 6, '05/01/2018 05:54:53', 2, 9, 'tabusuarios', 'Identificacao', 'Senha', '#a6afdd', 0, 6);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 7, '29/12/2017 11:03:24', 7, 7, 'usuario', 'login_usuario', 'senha_usuario', '#97c0d5', 1, 8);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 8, '16/04/2018 09:14:34', 2, 7, 'usuario', 'login_usuario', 'senha_usuario', '#aee8e8', 1, 9);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 9, '16/01/2018 03:46:57', 8, 11, 'usuario', 'login_usuario', 'senha_usuario', '#c2e7ed', 1, 10);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 10, '16/01/2018 10:14:17', 8, 12, 'usuario', 'login_usuario', 'senha_usuario', '#b9e4ea', 1, 11);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 11, '04/08/2018 04:59:40', 8, 5, 'usuario', 'login_usuario', 'senha_usuario', '#b9cad0', 1, 12);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 12, '05/02/2018 03:59:57', 8, 13, 'usuario', 'login_usuario', 'senha_usuario', '#ffbf80', 1, 13);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 13, '05/02/2018 10:30:17', 8, 14, 'usuario', 'login_usuario', 'senha_usuario', '#a0e0eb', 1, 15);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 14, '31/01/2018 02:21:50', 8, 11, 'usuario', 'login_usuario', 'senha_usuario', '#67c25c', 1, 16);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 15, '07/02/2018 05:24:31', 8, 6, 'usuario', 'login_usuario', 'senha_usuario', '#caeabf', 1, 17);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 16, '22/02/2018 10:02:38', 8, 4, 'usuario', 'login_usuario', 'senha_usuario', '#bae1b5', 1, 18);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 17, '22/03/2018 10:41:30', 4, 5, 'usuario', 'login_usuario', 'senha_usuario', '#a5e4d3', 1, 19);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 18, '02/04/2018 09:43:14', 8, 6, 'usuario', 'login_usuario', 'senha_usuario', '#9ecbb6', 1, 20);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 19, '21/05/2018 02:33:27', 4, 11, 'usuario', 'login_usuario', 'senha_usuario', '#6cd2c4', 1, 23);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 20, '14/06/2018 08:28:47', 4, 2, 'usuario', 'login_usuario', 'senha_usuario', '#9fcd81', 1, 24);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 21, '25/07/2018 02:43:52', 2, 11, 'usuario', 'login_usuario', 'senha_usuario', '#c8f0c6', 1, 25);
INSERT INTO config_login ( `id_config_login`, `descricao_config_login`, `imagem_fundo_id`, `imagem_icone_id`, `tabela_login_config_login`, `login_config_login`, `senha_config_login`, `cor_fundo_config_login`, `password_config_login`, `projetos_id`) VALUES ( 22, '05/08/2018 03:22:04', 2, 5, 'usuario', 'login_usuario', 'senha_usuario', '#9ed99b', 1, 26);