
-- Dados da tabela logica_negocio
-- Gerando em: 05/08/2018 23:35:05
-- Pelo Gerador JK-19

TRUNCATE `logica_negocio`;

-- Dados da tabela: 
INSERT INTO logica_negocio ( `id_logica_negocio`, `projetos_id`, `tabela_logica_negocio`, `campos_logica_negocio`, `campos_data_logica_negocio`, `campo_resultado_logica_negocio`, `tipo_reultado_logica_negocio`, `formula_id`, `usuario_id`, `bool_ativo_logica_negocio`) VALUES ( 1, 12, 'operacao_teste', 'valor_1_operacao_teste+valor_2_operacao_teste', '', 'resultado_operacao_teste', 'd', 1, 1, 1);
INSERT INTO logica_negocio ( `id_logica_negocio`, `projetos_id`, `tabela_logica_negocio`, `campos_logica_negocio`, `campos_data_logica_negocio`, `campo_resultado_logica_negocio`, `tipo_reultado_logica_negocio`, `formula_id`, `usuario_id`, `bool_ativo_logica_negocio`) VALUES ( 4, 12, 'operacao_teste', 'valor_3_operacao_teste+valor_4_operacao_teste', '', 'resultado_2_operacao_teste', 'd', 3, 1, 1);
INSERT INTO logica_negocio ( `id_logica_negocio`, `projetos_id`, `tabela_logica_negocio`, `campos_logica_negocio`, `campos_data_logica_negocio`, `campo_resultado_logica_negocio`, `tipo_reultado_logica_negocio`, `formula_id`, `usuario_id`, `bool_ativo_logica_negocio`) VALUES ( 5, 12, 'operacao_teste', 'resultado_operacao_teste+resultado_2_operacao_teste', '', 'resultado_final_operacao_teste', 'd', 9, 1, 1);
INSERT INTO logica_negocio ( `id_logica_negocio`, `projetos_id`, `tabela_logica_negocio`, `campos_logica_negocio`, `campos_data_logica_negocio`, `campo_resultado_logica_negocio`, `tipo_reultado_logica_negocio`, `formula_id`, `usuario_id`, `bool_ativo_logica_negocio`) VALUES ( 6, 13, 'item_orcamento', 'quantidade_item_orcamento+valor_unitario_item_orcamento', '', 'total_item_orcamento', 'd', 3, 1, 1);
INSERT INTO logica_negocio ( `id_logica_negocio`, `projetos_id`, `tabela_logica_negocio`, `campos_logica_negocio`, `campos_data_logica_negocio`, `campo_resultado_logica_negocio`, `tipo_reultado_logica_negocio`, `formula_id`, `usuario_id`, `bool_ativo_logica_negocio`) VALUES ( 7, 12, 'operacao_data', 'data_2_operacao_data', 'data_1_operacao_data', 'resultado_data_operacao_data', 's', 10, 1, 1);
INSERT INTO logica_negocio ( `id_logica_negocio`, `projetos_id`, `tabela_logica_negocio`, `campos_logica_negocio`, `campos_data_logica_negocio`, `campo_resultado_logica_negocio`, `tipo_reultado_logica_negocio`, `formula_id`, `usuario_id`, `bool_ativo_logica_negocio`) VALUES ( 8, 12, 'operacao_teste', 'valor_1_operacao_teste+valor_3_operacao_teste', '', 'valor_4_operacao_teste', 'd', 1, 1, 1);
INSERT INTO logica_negocio ( `id_logica_negocio`, `projetos_id`, `tabela_logica_negocio`, `campos_logica_negocio`, `campos_data_logica_negocio`, `campo_resultado_logica_negocio`, `tipo_reultado_logica_negocio`, `formula_id`, `usuario_id`, `bool_ativo_logica_negocio`) VALUES ( 9, 20, 'pedido_item', 'quantidade_pedido_item+valor_unitario_pedido_item', '', 'total_pedido_item', 'd', 3, 1, 1);
INSERT INTO logica_negocio ( `id_logica_negocio`, `projetos_id`, `tabela_logica_negocio`, `campos_logica_negocio`, `campos_data_logica_negocio`, `campo_resultado_logica_negocio`, `tipo_reultado_logica_negocio`, `formula_id`, `usuario_id`, `bool_ativo_logica_negocio`) VALUES ( 10, 23, 'orcamento_item', 'quantidade_orcamento_item+preco_orcamento_item', '', 'total_orcamento_item', 'd', 3, 1, 1);
INSERT INTO logica_negocio ( `id_logica_negocio`, `projetos_id`, `tabela_logica_negocio`, `campos_logica_negocio`, `campos_data_logica_negocio`, `campo_resultado_logica_negocio`, `tipo_reultado_logica_negocio`, `formula_id`, `usuario_id`, `bool_ativo_logica_negocio`) VALUES ( 11, 23, 'compra_item', 'quantidade_compra_item+valor_unitario_compra_item', '', 'total_compra_item', 'd', 3, 1, 1);
INSERT INTO logica_negocio ( `id_logica_negocio`, `projetos_id`, `tabela_logica_negocio`, `campos_logica_negocio`, `campos_data_logica_negocio`, `campo_resultado_logica_negocio`, `tipo_reultado_logica_negocio`, `formula_id`, `usuario_id`, `bool_ativo_logica_negocio`) VALUES ( 12, 23, 'pedido_item', 'quantidade_pedido_item+valor_unitario_pedido_item', '', 'total_pedido_item', 'd', 3, 1, 1);