insert into estado (descricao_estado, sigla_estado) values ("Acre" , 					"AC");
insert into estado (descricao_estado, sigla_estado) values ("Alagoas" , 				"AL");
insert into estado (descricao_estado, sigla_estado) values ("Amapá" , 					"AP");
insert into estado (descricao_estado, sigla_estado) values ("Amazonas" , 				"AM");
insert into estado (descricao_estado, sigla_estado) values ("Bahia" , 					"BA");
insert into estado (descricao_estado, sigla_estado) values ("Ceará" , 					"CE");
insert into estado (descricao_estado, sigla_estado) values ("Distrito Federal" , 		"DF");
insert into estado (descricao_estado, sigla_estado) values ("Espírito Santo" , 			"ES");
insert into estado (descricao_estado, sigla_estado) values ("Goiás" , 					"GO");
insert into estado (descricao_estado, sigla_estado) values ("Maranhão" , 				"MA");
insert into estado (descricao_estado, sigla_estado) values ("Mato Grosso" , 			"MT");
insert into estado (descricao_estado, sigla_estado) values ("Mato Grosso do Sul" , 		"MS");
insert into estado (descricao_estado, sigla_estado) values ("Minas Gerais" , 			"MG");
insert into estado (descricao_estado, sigla_estado) values ("Pará" 	,					"PA");
insert into estado (descricao_estado, sigla_estado) values ("Paraíba" , 				"PB");
insert into estado (descricao_estado, sigla_estado) values ("Paraná" , 					"PR");
insert into estado (descricao_estado, sigla_estado) values ("Pernambuco" , 				"PE");
insert into estado (descricao_estado, sigla_estado) values ("Piauí" , 					"PI");
insert into estado (descricao_estado, sigla_estado) values ("Rio de Janeiro" , 			"RJ");
insert into estado (descricao_estado, sigla_estado) values ("Rio Grande do Norte" , 	"RN");
insert into estado (descricao_estado, sigla_estado) values ("Rio Grande do Sul" , 		"RS");
insert into estado (descricao_estado, sigla_estado) values ("Rondônia" , 				"RO");
insert into estado (descricao_estado, sigla_estado) values ("Roraima" , 				"RR");
insert into estado (descricao_estado, sigla_estado) values ("Santa Catarina" , 			"SC");
insert into estado (descricao_estado, sigla_estado) values ("São Paulo" , 				"SP");
insert into estado (descricao_estado, sigla_estado) values ("Sergipe" , 				"SE");
insert into estado (descricao_estado, sigla_estado) values ("Tocantins" , 				"TO");